name: book_and_play
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.0-91.0.dev

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.3
  flutter_bloc: ^9.1.1
  flutter_native_splash: ^2.4.6
  country_picker: ^2.0.27
  chat_bubbles: ^1.7.0
  dartz: ^0.10.1
  dio: ^5.8.0+1
  logger: ^2.5.0
  get_it: ^8.0.3
  bloc: ^9.0.0
  google_maps_flutter: ^2.12.1
  location: ^8.0.0
  geolocator: ^14.0.0
  intl: ^0.20.2
  url_launcher: ^6.3.1
  image_picker: ^1.1.2
  dropdown_button2: ^2.3.9
  flutter_date_pickers: ^0.4.3
  awesome_snackbar_content: ^0.1.6
  flutter_svg: ^2.1.0
  flutter_datetime_picker_plus: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/gifs/
    - assets/map_styles/


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/book_and_play_logo.png"
  min_sdk_android: 21 



flutter_native_splash:
  #color: "#42a5f5"
  ios: true
  background_image: "assets/images/book_and_play_splash.png"


